import type { Property } from '../lib/properties'

export const GOOD_KECH_PROPERTIES: Property[] = [
  {
    id: 'gki-villa-amelkis',
    title: 'Villa contemporaine à Amelkis',
    location: 'Amelkis, Marrakech',
    city: 'Marrakech',
    price: '12 900 000',
    priceNum: 12900000,
    type: 'Villa',
    beds: 5,
    baths: 5,
    area: '620 m²',
    image: '/demos/good-kech-immo/villa-amelkis.webp',
    images: [
      '/demos/good-kech-immo/villa-amelkis.webp',
      '/demos/good-kech-immo/hero.webp',
      '/demos/good-kech-immo/villa-interior-1.webp',
      '/demos/good-kech-immo/villa-interior-2.webp',
    ],
    badge: 'Sélection',
    badgeColor: 'bg-amber-500',
    description:
      "Une villa contemporaine aux volumes généreux, pensée autour de la lumière et de la vie extérieure. Les espaces de réception s'ouvrent sur un jardin paysagé, une piscine et plusieurs terrasses. Une adresse calme à proximité des parcours de golf d'Amelkis.",
    features: ['Piscine privée', 'Jardin paysagé', '5 suites', 'Double salon', 'Cuisine équipée', 'Terrasses', 'Garage', 'Résidence sécurisée'],
  },
  {
    id: 'gki-appartement-hivernage',
    title: 'Appartement haut standing à Hivernage',
    location: 'Hivernage, Marrakech',
    city: 'Marrakech',
    price: '3 450 000',
    priceNum: 3450000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '185 m²',
    image: '/demos/good-kech-immo/hivernage.webp',
    images: [
      '/demos/good-kech-immo/hivernage.webp',
      '/demos/good-kech-immo/interior-light.webp',
      '/demos/good-kech-immo/interior-suite.webp',
      '/demos/good-kech-immo/villa-amelkis.webp',
    ],
    badge: 'Nouveau',
    badgeColor: 'bg-emerald-500',
    description:
      "Appartement lumineux au cœur de l'Hivernage, avec une distribution fluide et des finitions soignées. La pièce de vie et la suite principale profitent de belles ouvertures, dans une résidence de standing proche des adresses emblématiques du quartier.",
    features: ['3 chambres', 'Suite parentale', 'Terrasse', 'Climatisation', 'Cuisine équipée', 'Ascenseur', 'Parking', 'Résidence sécurisée'],
  },
  {
    id: 'gki-riad-medina',
    title: 'Riad de charme dans la Médina',
    location: 'Médina, Marrakech',
    city: 'Marrakech',
    price: '6 800 000',
    priceNum: 6800000,
    type: 'Riad',
    beds: 6,
    baths: 6,
    area: '410 m²',
    image: '/demos/good-kech-immo/riad-medina.webp',
    images: [
      '/demos/good-kech-immo/riad-medina.webp',
      '/demos/good-kech-immo/marrakech-architecture.webp',
      '/demos/good-kech-immo/medina-lane.webp',
      '/demos/good-kech-immo/marrakech-earth.webp',
    ],
    badge: 'Charme',
    badgeColor: 'bg-rose-500',
    description:
      "Un riad organisé autour d'un patio paisible, mêlant détails artisanaux et confort contemporain. Six chambres, plusieurs salons et une terrasse généreuse composent un lieu adapté à une résidence de caractère ou à un projet d'accueil.",
    features: ['Patio central', '6 chambres', 'Terrasse', 'Bassin', 'Salon marocain', 'Cuisine équipée', 'Climatisation', 'Accès facile'],
  },
  {
    id: 'gki-villa-ourika',
    title: "Villa avec piscine Route de l’Ourika",
    location: "Route de l’Ourika, Marrakech",
    city: 'Marrakech',
    price: '8 750 000',
    priceNum: 8750000,
    type: 'Villa',
    beds: 4,
    baths: 4,
    area: '520 m²',
    image: '/demos/good-kech-immo/villa-ourika.webp',
    images: [
      '/demos/good-kech-immo/villa-ourika.webp',
      '/demos/good-kech-immo/villa-exterior.webp',
      '/demos/good-kech-immo/interior-light.webp',
      '/demos/good-kech-immo/villa-pool.webp',
    ],
    badge: 'À découvrir',
    badgeColor: 'bg-amber-500',
    description:
      "Une propriété chaleureuse tournée vers les montagnes de l'Atlas, avec piscine, jardin et espaces de réception ouverts sur l'extérieur. Son plan privilégie les volumes simples et une circulation naturelle entre intérieur et terrasses.",
    features: ['Piscine', 'Jardin', '4 suites', 'Vue Atlas', 'Cheminée', 'Terrasses', 'Logement personnel', 'Parking'],
  },
  {
    id: 'gki-appartement-gueliz',
    title: 'Appartement moderne à Guéliz',
    location: 'Guéliz, Marrakech',
    city: 'Marrakech',
    price: '2 150 000',
    priceNum: 2150000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '118 m²',
    image: '/demos/good-kech-immo/gueliz.webp',
    images: [
      '/demos/good-kech-immo/gueliz.webp',
      '/demos/good-kech-immo/apartment-living.webp',
      '/demos/good-kech-immo/apartment-modern.webp',
      '/demos/good-kech-immo/apartment-kitchen.webp',
    ],
    badge: 'Opportunité',
    badgeColor: 'bg-emerald-500',
    description:
      "Un appartement contemporain et fonctionnel au centre de Guéliz. Le séjour profite d'une lumière généreuse et d'une cuisine ouverte, tandis que les deux chambres offrent un cadre calme à proximité immédiate des commerces et services.",
    features: ['2 chambres', 'Balcon', 'Cuisine ouverte', 'Climatisation', 'Ascenseur', 'Parking', 'Résidence récente', 'Proche commerces'],
  },
  {
    id: 'gki-terrain-tahanaout',
    title: 'Terrain idéal investissement Route de Tahanaout',
    location: 'Route de Tahanaout, Marrakech',
    city: 'Marrakech',
    price: '4 900 000',
    priceNum: 4900000,
    type: 'Terrain',
    beds: 0,
    baths: 0,
    area: '2 500 m²',
    image: '/demos/good-kech-immo/tahanaout.webp',
    images: [
      '/demos/good-kech-immo/tahanaout.webp',
      '/demos/good-kech-immo/marrakech-architecture.webp',
      '/demos/good-kech-immo/marrakech-earth.webp',
    ],
    badge: 'Investissement',
    badgeColor: 'bg-amber-500',
    description:
      "Une parcelle bien située sur la Route de Tahanaout, dans un environnement ouvert avec une belle perspective sur l'Atlas. Une base pertinente pour étudier un projet résidentiel ou d'investissement, sous réserve des vérifications urbanistiques usuelles.",
    features: ['2 500 m²', 'Accès routier', 'Vue dégagée', 'Proximité Marrakech', 'Environnement calme', 'Étude de projet possible'],
  },
]

export const GOOD_KECH_LOCATIONS = [
  { name: 'Hivernage', image: '/demos/good-kech-immo/marrakech-architecture.webp' },
  { name: 'Guéliz', image: '/demos/good-kech-immo/riad-medina.webp' },
  { name: 'Palmeraie', image: '/demos/good-kech-immo/tahanaout.webp' },
  { name: 'Amelkis', image: '/demos/good-kech-immo/villa-amelkis.webp' },
  { name: 'Agdal', image: '/demos/good-kech-immo/marrakech-earth.webp' },
  { name: "Route de l’Ourika", image: '/demos/good-kech-immo/villa-ourika.webp' },
]
