import type { Property } from '../lib/properties'

const IMAGES = {
  hero: '/demos/immo-built/test-agency-exterior.webp',
  villa: '/demos/immo-built/test-agency-villa.webp',
  villaAlt: '/demos/immo-built/test-agency-villa-2.webp',
  exterior: '/demos/immo-built/test-agency-exterior.webp',
  penthouse: '/demos/immo-built/test-agency-penthouse.webp',
  interior: '/demos/immo-built/test-agency-interior.webp',
  kitchen: '/demos/immo-built/test-agency-kitchen.webp',
  apartment: '/demos/immo-built/test-agency-apartment.webp',
  feature: '/demos/immo-built/test-agency-feature.webp',
  catalogue: '/demos/immo-built/test-agency-catalogue.webp',
}

export const AGENCE_REDA_PROPERTIES: Property[] = [
  {
    id: 'reda-appartement-hamria',
    title: 'Appartement lumineux à Hamria',
    location: 'Hamria, Meknès',
    city: 'Meknès',
    price: '1 350 000',
    priceNum: 1350000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '142 m²',
    image: IMAGES.penthouse,
    images: [IMAGES.penthouse, IMAGES.interior, IMAGES.kitchen, IMAGES.apartment],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Appartement lumineux et bien distribué au cœur de Hamria, avec un séjour généreux, trois chambres et des finitions contemporaines. Une annonce de démonstration pensée pour présenter le potentiel d’un bien urbain à Meknès.',
    features: ['3 chambres', '2 salles de bain', 'Séjour lumineux', 'Cuisine équipée', 'Balcon', 'Ascenseur', 'Parking', 'Proche commodités'],
  },
  {
    id: 'reda-villa-marjane',
    title: 'Villa contemporaine à Marjane',
    location: 'Marjane, Meknès',
    city: 'Meknès',
    price: '3 850 000',
    priceNum: 3850000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '390 m²',
    image: IMAGES.exterior,
    images: [IMAGES.exterior, IMAGES.villa, IMAGES.villaAlt, IMAGES.feature],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Villa contemporaine aux volumes confortables, organisée autour d’un jardin et de beaux espaces de réception. Les ouvertures généreuses créent une circulation naturelle entre l’intérieur et l’extérieur.',
    features: ['4 chambres', 'Jardin', 'Double salon', 'Cuisine équipée', 'Suite parentale', 'Terrasses', 'Garage', 'Quartier résidentiel'],
  },
  {
    id: 'reda-maison-toulal',
    title: 'Maison familiale à Toulal',
    location: 'Toulal, Meknès',
    city: 'Meknès',
    price: '2 250 000',
    priceNum: 2250000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '310 m²',
    image: IMAGES.villaAlt,
    images: [IMAGES.villaAlt, IMAGES.villa, IMAGES.interior, IMAGES.kitchen],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Maison familiale proposant quatre chambres, plusieurs espaces de vie et un extérieur facile à aménager. Une présentation réaliste pour illustrer une recherche résidentielle dans le secteur de Toulal.',
    features: ['4 chambres', '3 salles de bain', 'Salon familial', 'Cuisine équipée', 'Terrasse', 'Cour', 'Garage', 'Accès pratique'],
  },
  {
    id: 'reda-appartement-ville-nouvelle',
    title: 'Appartement moderne en Ville Nouvelle',
    location: 'Ville Nouvelle, Meknès',
    city: 'Meknès',
    price: '1 180 000',
    priceNum: 1180000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '108 m²',
    image: IMAGES.apartment,
    images: [IMAGES.apartment, IMAGES.interior, IMAGES.kitchen, IMAGES.penthouse],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Appartement moderne adapté à une vie citadine, avec une pièce de vie ouverte et deux chambres confortables. Son emplacement de démonstration met en avant la proximité des services de la Ville Nouvelle.',
    features: ['2 chambres', '2 salles de bain', 'Cuisine ouverte', 'Balcon', 'Climatisation', 'Ascenseur', 'Parking', 'Emplacement central'],
  },
  {
    id: 'reda-villa-plaisance',
    title: 'Villa avec jardin à Plaisance',
    location: 'Plaisance, Meknès',
    city: 'Meknès',
    price: '3 200 000',
    priceNum: 3200000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '350 m²',
    image: IMAGES.feature,
    images: [IMAGES.feature, IMAGES.exterior, IMAGES.villa, IMAGES.interior],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Villa familiale avec jardin, salon traversant et quatre chambres. Les espaces sont présentés de façon claire pour aider le visiteur à se projeter dans une maison confortable à Plaisance.',
    features: ['4 chambres', 'Jardin', 'Suite parentale', 'Séjour traversant', 'Cuisine équipée', 'Terrasse', 'Garage', 'Environnement calme'],
  },
  {
    id: 'reda-terrain-agourai',
    title: 'Terrain pour projet résidentiel',
    location: "Route d'Agourai, Meknès",
    city: 'Meknès',
    price: '1 650 000',
    priceNum: 1650000,
    type: 'Terrain',
    beds: 0,
    baths: 0,
    area: '920 m²',
    image: IMAGES.catalogue,
    images: [IMAGES.catalogue, IMAGES.hero, IMAGES.exterior, IMAGES.villaAlt],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Terrain présenté comme exemple d’opportunité résidentielle aux environs de Meknès. Les informations foncières, urbanistiques et les possibilités de construction seraient à confirmer avant toute acquisition.',
    features: ['920 m²', 'Projet résidentiel', 'Accès routier', 'Environnement ouvert', 'Informations à vérifier', 'Visite sur rendez-vous'],
  },
]

export const AGENCE_REDA_AREAS = [
  { name: 'Hamria', detail: 'Vie urbaine et appartements', image: IMAGES.penthouse },
  { name: 'Marjane', detail: 'Villas et résidences', image: IMAGES.exterior },
  { name: 'Toulal', detail: 'Maisons familiales', image: IMAGES.villaAlt },
  { name: 'Ville Nouvelle', detail: 'Central et pratique', image: IMAGES.apartment },
  { name: 'Plaisance', detail: 'Calme et espaces verts', image: IMAGES.feature },
  { name: "Route d'Agourai", detail: 'Terrains et projets', image: IMAGES.catalogue },
]
