import type { Property } from '../lib/properties'

export const IMMO_BUILT_PROPERTIES: Property[] = [
  {
    id: 'ib-appartement-cfc',
    title: 'Appartement haut standing à Casablanca Finance City',
    location: 'Casablanca Finance City, Casablanca',
    city: 'Casablanca',
    price: '3 200 000',
    priceNum: 3200000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '165 m²',
    image: '/demos/immo-built/test-agency-villa.webp',
    images: [
      '/demos/immo-built/test-agency-villa.webp',
      '/demos/immo-built/test-agency-villa-2.webp',
      '/demos/immo-built/test-agency-interior.webp',
      '/demos/immo-built/test-agency-kitchen.webp',
    ],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      "Appartement contemporain dans un environnement urbain recherché. Les volumes sont bien distribués, avec un séjour lumineux, une cuisine équipée et trois chambres adaptées à une vie familiale au cœur de Casablanca.",
    features: ['3 chambres', 'Suite parentale', 'Séjour lumineux', 'Cuisine équipée', 'Climatisation', 'Terrasse', 'Parking', 'Résidence sécurisée'],
  },
  {
    id: 'ib-appartement-racine',
    title: 'Appartement moderne à Racine',
    location: 'Racine, Casablanca',
    city: 'Casablanca',
    price: '2 700 000',
    priceNum: 2700000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '128 m²',
    image: '/demos/immo-built/test-agency-penthouse.webp',
    images: [
      '/demos/immo-built/test-agency-penthouse.webp',
      '/demos/immo-built/test-agency-interior.webp',
      '/demos/immo-built/test-agency-kitchen.webp',
      '/demos/immo-built/test-agency-apartment.webp',
    ],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      "Un appartement fonctionnel et soigné à Racine, pensé pour un quotidien urbain confortable. L'espace de vie ouvert profite d'une belle lumière naturelle et les deux chambres offrent calme et intimité.",
    features: ['2 chambres', '2 salles de bain', 'Cuisine ouverte', 'Balcon', 'Climatisation', 'Ascenseur', 'Parking', 'Proche commerces'],
  },
  {
    id: 'ib-villa-californie',
    title: 'Villa contemporaine à Californie',
    location: 'Californie, Casablanca',
    city: 'Casablanca',
    price: '8 900 000',
    priceNum: 8900000,
    type: 'Villa',
    beds: 4,
    baths: 4,
    area: '480 m²',
    image: '/demos/immo-built/test-agency-exterior.webp',
    images: [
      '/demos/immo-built/test-agency-exterior.webp',
      '/demos/immo-built/test-agency-villa.webp',
      '/demos/immo-built/test-agency-villa-2.webp',
      '/demos/immo-built/test-agency-feature.webp',
    ],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      "Villa aux lignes contemporaines avec de larges ouvertures sur le jardin. Les espaces de réception sont organisés autour d'une circulation simple entre intérieur, terrasse et piscine.",
    features: ['4 suites', 'Piscine', 'Jardin', 'Double salon', 'Cuisine équipée', 'Terrasses', 'Garage', 'Quartier résidentiel'],
  },
  {
    id: 'ib-appartement-gauthier',
    title: 'Appartement avec terrasse à Gauthier',
    location: 'Gauthier, Casablanca',
    city: 'Casablanca',
    price: '2 400 000',
    priceNum: 2400000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '118 m²',
    image: '/demos/immo-built/test-agency-apartment.webp',
    images: [
      '/demos/immo-built/test-agency-apartment.webp',
      '/demos/immo-built/test-agency-interior.webp',
      '/demos/immo-built/test-agency-kitchen.webp',
      '/demos/immo-built/test-agency-penthouse.webp',
    ],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      "Appartement lumineux avec terrasse dans le quartier Gauthier. Son séjour ouvert, ses deux chambres et ses finitions sobres composent un bien adapté à un mode de vie central et pratique.",
    features: ['Terrasse', '2 chambres', 'Cuisine équipée', 'Climatisation', 'Double vitrage', 'Ascenseur', 'Parking', 'Emplacement central'],
  },
  {
    id: 'ib-residence-ain-diab',
    title: 'Résidence premium à Ain Diab',
    location: 'Ain Diab, Casablanca',
    city: 'Casablanca',
    price: '4 150 000',
    priceNum: 4150000,
    type: 'Appartement',
    beds: 3,
    baths: 3,
    area: '190 m²',
    image: '/demos/immo-built/test-agency-catalogue.webp',
    images: [
      '/demos/immo-built/test-agency-catalogue.webp',
      '/demos/immo-built/test-agency-penthouse.webp',
      '/demos/immo-built/test-agency-interior.webp',
      '/demos/immo-built/test-agency-apartment.webp',
    ],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      "Un appartement aux volumes généreux dans une résidence contemporaine à Ain Diab. La pièce de vie s'ouvre sur une terrasse et les trois chambres disposent d'espaces confortables et bien organisés.",
    features: ['3 chambres', 'Terrasse', 'Suite parentale', 'Cuisine équipée', 'Climatisation', '2 parkings', 'Ascenseur', 'Résidence sécurisée'],
  },
  {
    id: 'ib-appartement-oasis',
    title: 'Appartement familial à Oasis',
    location: 'Oasis, Casablanca',
    city: 'Casablanca',
    price: '2 650 000',
    priceNum: 2650000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '155 m²',
    image: '/demos/immo-built/test-agency-feature.webp',
    images: [
      '/demos/immo-built/test-agency-feature.webp',
      '/demos/immo-built/test-agency-apartment.webp',
      '/demos/immo-built/test-agency-kitchen.webp',
      '/demos/immo-built/test-agency-interior.webp',
    ],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      "Appartement familial bien agencé à Oasis, avec un séjour généreux, trois chambres et des rangements intégrés. Une proposition de démonstration pensée pour conjuguer espace, calme et accessibilité.",
    features: ['3 chambres', '2 salles de bain', 'Balcon', 'Rangements', 'Cuisine équipée', 'Climatisation', 'Parking', 'Résidence calme'],
  },
]

export const IMMO_BUILT_AREAS = [
  { name: 'CFC', detail: 'Architecture et vie urbaine', image: '/demos/immo-built/test-agency-hero.webp' },
  { name: 'Ain Diab', detail: 'Littoral et résidences', image: '/demos/immo-built/test-agency-penthouse.webp' },
  { name: 'Racine', detail: 'Central et résidentiel', image: '/demos/immo-built/test-agency-interior.webp' },
  { name: 'Gauthier', detail: 'Vie de quartier', image: '/demos/immo-built/test-agency-apartment.webp' },
  { name: 'Californie', detail: 'Villas et espaces verts', image: '/demos/immo-built/test-agency-exterior.webp' },
  { name: 'Oasis', detail: 'Calme et accessibilité', image: '/demos/immo-built/test-agency-villa-2.webp' },
]
