import type { Property } from '../lib/properties'

const IMAGES = {
  hero: '/demos/immo-built/test-agency-hero.webp',
  villa: '/demos/immo-built/test-agency-villa.webp',
  villaAlt: '/demos/immo-built/test-agency-villa-2.webp',
  exterior: '/demos/immo-built/test-agency-exterior.webp',
  penthouse: '/demos/immo-built/test-agency-penthouse.webp',
  interior: '/demos/immo-built/test-agency-interior.webp',
  kitchen: '/demos/immo-built/test-agency-kitchen.webp',
  apartment: '/demos/immo-built/test-agency-apartment.webp',
  feature: '/demos/immo-built/test-agency-feature.webp',
  catalogue: '/demos/immo-built/test-agency-catalogue.webp',
}

export const ELADIMMO_PROPERTIES: Property[] = [
  {
    id: 'ela-appartement-hay-riad',
    title: 'Appartement haut standing à Hay Riad',
    location: 'Hay Riad, Rabat',
    city: 'Rabat',
    price: '2 950 000',
    priceNum: 2950000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '168 m²',
    image: IMAGES.penthouse,
    images: [IMAGES.penthouse, IMAGES.interior, IMAGES.kitchen, IMAGES.apartment],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Appartement lumineux aux volumes généreux, avec un séjour ouvert, trois chambres et une terrasse. Une proposition de démonstration pensée pour un quotidien confortable à Hay Riad.',
    features: ['3 chambres', 'Suite parentale', 'Terrasse', 'Cuisine équipée', 'Climatisation', 'Ascenseur', 'Parking', 'Résidence sécurisée'],
  },
  {
    id: 'ela-villa-souissi',
    title: 'Villa contemporaine à Souissi',
    location: 'Souissi, Rabat',
    city: 'Rabat',
    price: '9 600 000',
    priceNum: 9600000,
    type: 'Villa',
    beds: 5,
    baths: 4,
    area: '520 m²',
    image: IMAGES.exterior,
    images: [IMAGES.exterior, IMAGES.villa, IMAGES.villaAlt, IMAGES.feature],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Villa contemporaine organisée autour de beaux espaces de réception et d’un jardin avec piscine. Les lignes sobres et les larges ouvertures offrent une atmosphère lumineuse et élégante.',
    features: ['5 chambres', 'Piscine', 'Jardin', 'Double salon', 'Cuisine équipée', 'Terrasses', 'Garage', 'Quartier résidentiel'],
  },
  {
    id: 'ela-appartement-agdal',
    title: 'Appartement moderne à Agdal',
    location: 'Agdal, Rabat',
    city: 'Rabat',
    price: '1 850 000',
    priceNum: 1850000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '112 m²',
    image: IMAGES.apartment,
    images: [IMAGES.apartment, IMAGES.interior, IMAGES.kitchen, IMAGES.penthouse],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Appartement moderne et bien agencé au cœur d’Agdal. Le séjour bénéficie d’une belle lumière naturelle et les espaces ont été pensés pour une vie urbaine pratique.',
    features: ['2 chambres', '2 salles de bain', 'Balcon', 'Cuisine équipée', 'Climatisation', 'Ascenseur', 'Parking', 'Proche commodités'],
  },
  {
    id: 'ela-villa-harhoura',
    title: 'Villa avec piscine à Harhoura',
    location: 'Harhoura, Témara',
    city: 'Rabat',
    price: '4 350 000',
    priceNum: 4350000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '360 m²',
    image: IMAGES.villaAlt,
    images: [IMAGES.villaAlt, IMAGES.exterior, IMAGES.villa, IMAGES.feature],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Villa familiale avec piscine et espaces extérieurs agréables à Harhoura. La distribution privilégie la lumière, la convivialité et la continuité entre intérieur et jardin.',
    features: ['4 chambres', 'Piscine', 'Jardin', 'Séjour traversant', 'Cuisine équipée', 'Terrasse', 'Garage', 'Environnement résidentiel'],
  },
  {
    id: 'ela-appartement-wifak',
    title: 'Appartement familial à Wifak',
    location: 'Wifak, Témara',
    city: 'Rabat',
    price: '1 420 000',
    priceNum: 1420000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '136 m²',
    image: IMAGES.feature,
    images: [IMAGES.feature, IMAGES.apartment, IMAGES.kitchen, IMAGES.interior],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Appartement familial fonctionnel à Wifak, avec trois chambres, des rangements et une pièce de vie confortable. Une présentation de démonstration adaptée aux besoins du quotidien.',
    features: ['3 chambres', '2 salles de bain', 'Balcon', 'Rangements', 'Cuisine équipée', 'Ascenseur', 'Parking', 'Résidence calme'],
  },
  {
    id: 'ela-terrain-ain-atiq',
    title: 'Terrain pour projet résidentiel à Aïn Atiq',
    location: 'Aïn Atiq, Témara',
    city: 'Rabat',
    price: '2 100 000',
    priceNum: 2100000,
    type: 'Terrain',
    beds: 0,
    baths: 0,
    area: '780 m²',
    image: IMAGES.catalogue,
    images: [IMAGES.catalogue, IMAGES.hero, IMAGES.exterior, IMAGES.villaAlt],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Terrain présenté comme exemple de projet résidentiel dans le secteur d’Aïn Atiq. Les informations urbanistiques et juridiques seraient à confirmer avant toute décision d’acquisition.',
    features: ['780 m²', 'Projet résidentiel', 'Accès routier', 'Environnement en développement', 'Informations à vérifier', 'Visite sur rendez-vous'],
  },
]

export const ELADIMMO_AREAS = [
  { name: 'Hay Riad', detail: 'Appartements et résidences', image: IMAGES.penthouse },
  { name: 'Agdal', detail: 'Central et urbain', image: IMAGES.apartment },
  { name: 'Souissi', detail: 'Villas et grands espaces', image: IMAGES.exterior },
  { name: 'Harhoura', detail: 'Résidentiel proche du littoral', image: IMAGES.villaAlt },
  { name: 'Wifak', detail: 'Vie familiale à Témara', image: IMAGES.feature },
  { name: 'Aïn Atiq', detail: 'Projets et opportunités', image: IMAGES.catalogue },
]
