import type { Property } from '../lib/properties'

const IMAGES = {
  hero: '/demos/immo-built/test-agency-exterior.webp',
  villa: '/demos/immo-built/test-agency-villa.webp',
  villaAlt: '/demos/immo-built/test-agency-villa-2.webp',
  exterior: '/demos/immo-built/test-agency-exterior.webp',
  penthouse: '/demos/immo-built/test-agency-penthouse.webp',
  interior: '/demos/immo-built/test-agency-interior.webp',
  kitchen: '/demos/immo-built/test-agency-kitchen.webp',
  apartment: '/demos/immo-built/test-agency-apartment.webp',
  feature: '/demos/immo-built/test-agency-feature.webp',
  catalogue: '/demos/immo-built/test-agency-catalogue.webp',
}

export const IMRAN_PROPERTIES: Property[] = [
  {
    id: 'imran-appartement-sidi-bouzid',
    title: 'Appartement lumineux à Sidi Bouzid',
    location: 'Sidi Bouzid, Safi',
    city: 'Safi',
    price: '1 280 000',
    priceNum: 1280000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '132 m²',
    image: IMAGES.penthouse,
    images: [IMAGES.penthouse, IMAGES.interior, IMAGES.kitchen, IMAGES.apartment],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Appartement lumineux présenté à titre de démonstration, avec trois chambres, un séjour généreux et des espaces bien distribués dans le secteur recherché de Sidi Bouzid.',
    features: ['3 chambres', '2 salles de bain', 'Séjour lumineux', 'Cuisine équipée', 'Balcon', 'Ascenseur', 'Parking', 'Proche commodités'],
  },
  {
    id: 'imran-villa-corniche',
    title: 'Villa contemporaine proche de la corniche',
    location: 'Corniche, Safi',
    city: 'Safi',
    price: '3 450 000',
    priceNum: 3450000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '370 m²',
    image: IMAGES.exterior,
    images: [IMAGES.exterior, IMAGES.villa, IMAGES.villaAlt, IMAGES.feature],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Villa contemporaine de démonstration offrant de beaux volumes, un jardin agréable et une circulation fluide entre les espaces de réception et l’extérieur.',
    features: ['4 chambres', '3 salles de bain', 'Jardin', 'Double salon', 'Suite parentale', 'Terrasses', 'Garage', 'Proche corniche'],
  },
  {
    id: 'imran-appartement-plateau',
    title: 'Appartement moderne au Plateau',
    location: 'Plateau, Safi',
    city: 'Safi',
    price: '920 000',
    priceNum: 920000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '104 m²',
    image: IMAGES.apartment,
    images: [IMAGES.apartment, IMAGES.interior, IMAGES.kitchen, IMAGES.penthouse],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Appartement moderne adapté à une vie citadine, avec une pièce de vie conviviale, deux chambres confortables et un emplacement pratique au Plateau.',
    features: ['2 chambres', '2 salles de bain', 'Cuisine ouverte', 'Balcon', 'Climatisation', 'Ascenseur', 'Parking', 'Emplacement central'],
  },
  {
    id: 'imran-maison-ville-nouvelle',
    title: 'Maison familiale en Ville Nouvelle',
    location: 'Ville Nouvelle, Safi',
    city: 'Safi',
    price: '2 150 000',
    priceNum: 2150000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '295 m²',
    image: IMAGES.villaAlt,
    images: [IMAGES.villaAlt, IMAGES.villa, IMAGES.interior, IMAGES.kitchen],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Maison familiale de démonstration réunissant quatre chambres, plusieurs espaces de vie et une terrasse agréable au cœur de la Ville Nouvelle.',
    features: ['4 chambres', '3 salles de bain', 'Salon familial', 'Cuisine équipée', 'Terrasse', 'Cour', 'Garage', 'Accès pratique'],
  },
  {
    id: 'imran-appartement-hay-salam',
    title: 'Appartement familial à Hay Salam',
    location: 'Hay Salam, Safi',
    city: 'Safi',
    price: '780 000',
    priceNum: 780000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '116 m²',
    image: IMAGES.interior,
    images: [IMAGES.interior, IMAGES.apartment, IMAGES.kitchen, IMAGES.penthouse],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Appartement familial bien agencé avec trois chambres et une pièce de vie confortable. Cette annonce de démonstration illustre une recherche résidentielle à Hay Salam.',
    features: ['3 chambres', '2 salles de bain', 'Salon lumineux', 'Cuisine équipée', 'Balcon', 'Rangements', 'Parking', 'Quartier résidentiel'],
  },
  {
    id: 'imran-terrain-route-oualidia',
    title: 'Terrain pour projet résidentiel',
    location: "Route d'Oualidia, Safi",
    city: 'Safi',
    price: '1 550 000',
    priceNum: 1550000,
    type: 'Terrain',
    beds: 0,
    baths: 0,
    area: '940 m²',
    image: IMAGES.catalogue,
    images: [IMAGES.catalogue, IMAGES.hero, IMAGES.exterior, IMAGES.villaAlt],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Terrain présenté comme exemple d’opportunité résidentielle aux environs de Safi. Les informations foncières, urbanistiques et les possibilités de construction seraient à confirmer avant toute acquisition.',
    features: ['940 m²', 'Projet résidentiel', 'Accès routier', 'Environnement ouvert', 'Informations à vérifier', 'Visite sur rendez-vous'],
  },
]

export const IMRAN_AREAS = [
  { name: 'Sidi Bouzid', detail: 'Résidences proches du littoral', image: IMAGES.penthouse },
  { name: 'Corniche', detail: 'Cadre côtier et villas', image: IMAGES.exterior },
  { name: 'Plateau', detail: 'Vie urbaine et appartements', image: IMAGES.apartment },
  { name: 'Ville Nouvelle', detail: 'Central et pratique', image: IMAGES.villaAlt },
  { name: 'Hay Salam', detail: 'Quartiers résidentiels', image: IMAGES.interior },
  { name: "Route d'Oualidia", detail: 'Terrains et projets', image: IMAGES.catalogue },
]
