import type { Property } from '../lib/properties'

const IMAGES = {
  hero: '/demos/immo-built/test-agency-exterior.webp',
  villa: '/demos/immo-built/test-agency-villa.webp',
  villaAlt: '/demos/immo-built/test-agency-villa-2.webp',
  exterior: '/demos/immo-built/test-agency-exterior.webp',
  penthouse: '/demos/immo-built/test-agency-penthouse.webp',
  interior: '/demos/immo-built/test-agency-interior.webp',
  kitchen: '/demos/immo-built/test-agency-kitchen.webp',
  apartment: '/demos/immo-built/test-agency-apartment.webp',
  feature: '/demos/immo-built/test-agency-feature.webp',
  catalogue: '/demos/immo-built/test-agency-catalogue.webp',
}

export const ASMAE_PROPERTIES: Property[] = [
  {
    id: 'asmae-appartement-marchica',
    title: 'Appartement avec vue sur Marchica',
    location: 'Marchica, Nador',
    city: 'Nador',
    price: '1 480 000',
    priceNum: 1480000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '136 m²',
    image: IMAGES.penthouse,
    images: [IMAGES.penthouse, IMAGES.interior, IMAGES.kitchen, IMAGES.apartment],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Appartement lumineux présenté à titre de démonstration, avec une pièce de vie ouverte, trois chambres et une vue dégagée vers la lagune de Marchica. Une adresse pensée pour profiter pleinement du cadre de vie de Nador.',
    features: ['3 chambres', '2 salles de bain', 'Vue dégagée', 'Cuisine équipée', 'Balcon', 'Ascenseur', 'Parking', 'Proche commodités'],
  },
  {
    id: 'asmae-appartement-hay-al-matar',
    title: 'Appartement familial à Hay Al Matar',
    location: 'Hay Al Matar, Nador',
    city: 'Nador',
    price: '1 120 000',
    priceNum: 1120000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '124 m²',
    image: IMAGES.apartment,
    images: [IMAGES.apartment, IMAGES.interior, IMAGES.kitchen, IMAGES.penthouse],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Appartement familial aux volumes équilibrés dans le secteur de Hay Al Matar. Le séjour confortable, les trois chambres et les rangements composent un intérieur pratique pour une vie quotidienne sereine.',
    features: ['3 chambres', '2 salles de bain', 'Salon familial', 'Cuisine équipée', 'Balcon', 'Ascenseur', 'Parking', 'Quartier résidentiel'],
  },
  {
    id: 'asmae-villa-selouane',
    title: 'Villa contemporaine à Selouane',
    location: 'Selouane, Nador',
    city: 'Nador',
    price: '3 250 000',
    priceNum: 3250000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '360 m²',
    image: IMAGES.exterior,
    images: [IMAGES.exterior, IMAGES.villa, IMAGES.villaAlt, IMAGES.feature],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Villa contemporaine de démonstration organisée autour de beaux espaces de réception et d’un jardin facile à vivre. Ses ouvertures généreuses offrent une circulation naturelle entre intérieur et extérieur.',
    features: ['4 chambres', '3 salles de bain', 'Jardin', 'Double salon', 'Suite parentale', 'Terrasses', 'Garage', 'Environnement calme'],
  },
  {
    id: 'asmae-appartement-centre-ville',
    title: 'Appartement moderne au centre-ville',
    location: 'Centre-ville, Nador',
    city: 'Nador',
    price: '980 000',
    priceNum: 980000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '102 m²',
    image: IMAGES.interior,
    images: [IMAGES.interior, IMAGES.apartment, IMAGES.kitchen, IMAGES.penthouse],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Appartement moderne adapté à une vie citadine, avec une pièce de vie conviviale et deux chambres confortables. Sa situation centrale permet de rejoindre facilement commerces et services.',
    features: ['2 chambres', '2 salles de bain', 'Cuisine ouverte', 'Climatisation', 'Ascenseur', 'Balcon', 'Parking', 'Emplacement central'],
  },
  {
    id: 'asmae-maison-corniche',
    title: 'Maison élégante proche de la corniche',
    location: 'Corniche, Nador',
    city: 'Nador',
    price: '2 750 000',
    priceNum: 2750000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '305 m²',
    image: IMAGES.feature,
    images: [IMAGES.feature, IMAGES.villaAlt, IMAGES.interior, IMAGES.exterior],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Maison de démonstration aux espaces chaleureux, située à proximité de la corniche de Nador. Elle réunit quatre chambres, des pièces de réception lumineuses et un extérieur agréable.',
    features: ['4 chambres', '3 salles de bain', 'Salon lumineux', 'Cuisine équipée', 'Terrasse', 'Cour', 'Garage', 'Proche corniche'],
  },
  {
    id: 'asmae-terrain-arekmane',
    title: 'Terrain pour projet résidentiel',
    location: "Route d'Arekmane, Nador",
    city: 'Nador',
    price: '1 390 000',
    priceNum: 1390000,
    type: 'Terrain',
    beds: 0,
    baths: 0,
    area: '850 m²',
    image: IMAGES.catalogue,
    images: [IMAGES.catalogue, IMAGES.hero, IMAGES.exterior, IMAGES.villaAlt],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Terrain présenté comme exemple d’opportunité résidentielle aux environs de Nador. Les informations foncières, urbanistiques et les possibilités de construction seraient à confirmer avant toute acquisition.',
    features: ['850 m²', 'Projet résidentiel', 'Accès routier', 'Environnement ouvert', 'Informations à vérifier', 'Visite sur rendez-vous'],
  },
]

export const ASMAE_AREAS = [
  { name: 'Marchica', detail: 'Lagune et vues dégagées', image: IMAGES.penthouse },
  { name: 'Hay Al Matar', detail: 'Résidences et vie familiale', image: IMAGES.apartment },
  { name: 'Centre-ville', detail: 'Central et pratique', image: IMAGES.interior },
  { name: 'Corniche', detail: 'Cadre côtier recherché', image: IMAGES.feature },
  { name: 'Selouane', detail: 'Villas et maisons', image: IMAGES.exterior },
  { name: "Route d'Arekmane", detail: 'Terrains et projets', image: IMAGES.catalogue },
]
