import type { Property } from '../lib/properties'

const IMAGES = {
  hero: '/demos/immo-built/test-agency-exterior.webp',
  villa: '/demos/immo-built/test-agency-villa.webp',
  villaAlt: '/demos/immo-built/test-agency-villa-2.webp',
  exterior: '/demos/immo-built/test-agency-exterior.webp',
  penthouse: '/demos/immo-built/test-agency-penthouse.webp',
  interior: '/demos/immo-built/test-agency-interior.webp',
  kitchen: '/demos/immo-built/test-agency-kitchen.webp',
  apartment: '/demos/immo-built/test-agency-apartment.webp',
  feature: '/demos/immo-built/test-agency-feature.webp',
  catalogue: '/demos/immo-built/test-agency-catalogue.webp',
}

export const IMMOBAZ_PROPERTIES: Property[] = [
  {
    id: 'immobaz-appartement-marina',
    title: 'Appartement lumineux à la Marina',
    location: 'Marina, Agadir',
    city: 'Agadir',
    price: '2 350 000',
    priceNum: 2350000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '118 m²',
    image: IMAGES.penthouse,
    images: [IMAGES.penthouse, IMAGES.interior, IMAGES.kitchen, IMAGES.apartment],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Appartement lumineux présenté à titre de démonstration, avec une pièce de vie ouverte, deux chambres et des espaces confortables à proximité de la Marina d’Agadir.',
    features: ['2 chambres', '2 salles de bain', 'Séjour lumineux', 'Cuisine équipée', 'Terrasse', 'Ascenseur', 'Parking', 'Proche Marina'],
  },
  {
    id: 'immobaz-villa-founty',
    title: 'Villa contemporaine à Founty',
    location: 'Founty, Agadir',
    city: 'Agadir',
    price: '5 200 000',
    priceNum: 5200000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '410 m²',
    image: IMAGES.exterior,
    images: [IMAGES.exterior, IMAGES.villa, IMAGES.villaAlt, IMAGES.feature],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Villa contemporaine de démonstration offrant de beaux volumes, un jardin agréable et une circulation fluide entre les espaces intérieurs et extérieurs.',
    features: ['4 chambres', '3 salles de bain', 'Jardin', 'Double salon', 'Suite parentale', 'Terrasses', 'Garage', 'Quartier résidentiel'],
  },
  {
    id: 'immobaz-appartement-haut-founty',
    title: 'Appartement moderne à Haut Founty',
    location: 'Haut Founty, Agadir',
    city: 'Agadir',
    price: '1 450 000',
    priceNum: 1450000,
    type: 'Appartement',
    beds: 3,
    baths: 2,
    area: '126 m²',
    image: IMAGES.apartment,
    images: [IMAGES.apartment, IMAGES.interior, IMAGES.kitchen, IMAGES.penthouse],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Appartement moderne adapté à une vie familiale, avec trois chambres, une cuisine fonctionnelle et un séjour convivial dans le secteur de Haut Founty.',
    features: ['3 chambres', '2 salles de bain', 'Cuisine équipée', 'Balcon', 'Climatisation', 'Ascenseur', 'Parking', 'Résidence récente'],
  },
  {
    id: 'immobaz-appartement-sonaba',
    title: 'Appartement avec terrasse à Sonaba',
    location: 'Sonaba, Agadir',
    city: 'Agadir',
    price: '1 880 000',
    priceNum: 1880000,
    type: 'Appartement',
    beds: 2,
    baths: 2,
    area: '112 m²',
    image: IMAGES.interior,
    images: [IMAGES.interior, IMAGES.apartment, IMAGES.kitchen, IMAGES.penthouse],
    badge: 'Démo',
    badgeColor: 'bg-amber-500',
    description:
      'Appartement de démonstration avec une terrasse agréable, deux chambres et des finitions contemporaines dans le quartier résidentiel de Sonaba.',
    features: ['2 chambres', '2 salles de bain', 'Terrasse', 'Cuisine ouverte', 'Climatisation', 'Ascenseur', 'Parking', 'Proche littoral'],
  },
  {
    id: 'immobaz-maison-dakhla',
    title: 'Maison familiale à Dakhla',
    location: 'Dakhla, Agadir',
    city: 'Agadir',
    price: '2 450 000',
    priceNum: 2450000,
    type: 'Villa',
    beds: 4,
    baths: 3,
    area: '285 m²',
    image: IMAGES.villaAlt,
    images: [IMAGES.villaAlt, IMAGES.villa, IMAGES.interior, IMAGES.kitchen],
    badge: 'Démo',
    badgeColor: 'bg-rose-500',
    description:
      'Maison familiale bien distribuée avec quatre chambres, plusieurs espaces de vie et une terrasse. Cette annonce de démonstration illustre une recherche résidentielle à Dakhla.',
    features: ['4 chambres', '3 salles de bain', 'Salon familial', 'Cuisine équipée', 'Terrasse', 'Cour', 'Garage', 'Accès pratique'],
  },
  {
    id: 'immobaz-terrain-taghazout',
    title: 'Terrain pour projet résidentiel',
    location: 'Route de Taghazout, Agadir',
    city: 'Agadir',
    price: '2 100 000',
    priceNum: 2100000,
    type: 'Terrain',
    beds: 0,
    baths: 0,
    area: '980 m²',
    image: IMAGES.catalogue,
    images: [IMAGES.catalogue, IMAGES.hero, IMAGES.exterior, IMAGES.villaAlt],
    badge: 'Démo',
    badgeColor: 'bg-emerald-500',
    description:
      'Terrain présenté comme exemple d’opportunité résidentielle aux environs d’Agadir. Les informations foncières, urbanistiques et les possibilités de construction seraient à confirmer avant toute acquisition.',
    features: ['980 m²', 'Projet résidentiel', 'Accès routier', 'Environnement ouvert', 'Informations à vérifier', 'Visite sur rendez-vous'],
  },
]

export const IMMOBAZ_AREAS = [
  { name: 'Marina', detail: 'Appartements et bord de mer', image: IMAGES.penthouse },
  { name: 'Founty', detail: 'Villas et résidences', image: IMAGES.exterior },
  { name: 'Haut Founty', detail: 'Vie familiale et moderne', image: IMAGES.apartment },
  { name: 'Sonaba', detail: 'Résidentiel proche du littoral', image: IMAGES.interior },
  { name: 'Dakhla', detail: 'Maisons et appartements', image: IMAGES.villaAlt },
  { name: 'Route de Taghazout', detail: 'Terrains et projets', image: IMAGES.catalogue },
]
